apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-master.conf: |
    # Redis configuration for the master
    bind 0.0.0.0
    protected-mode no
    port 6379
    appendonly yes
    # Additional configuration for the master
    replica-serve-stale-data yes

  redis-slave.conf: |
    # Redis configuration for the slave
    bind 0.0.0.0
    protected-mode no
    port 6379
    appendonly yes
    # Additional configuration for the slave
    replicaof redis-master 6379
