apiVersion: v1
kind: Service
metadata:
  name: barkeleyapp-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30000
  selector:
    app: barkeley
---
apiVersion: v1
kind: Service
metadata:
  name: barkeleyapp-lb
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-058232f3116bc5fcb"
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8000"
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/healthz"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: barkeley
